scrape_configs:
  - job_name: 'ec2_instances'
    scrape_interval: 5s
    ec2_sd_configs:
      - region: us-west-1
        port: 9100
        filters:
          - name: tag:Name
            values:
              - Node-Exporter
