---
# Variables specific to Prometheus servers
# Extends the base Ubuntu configuration

# Prometheus-specific packages
update_ubuntu_host_additional_packages:
  - htop
  - vim
  - curl
  - net-tools
  - software-properties-common
  - python3
  - python3-pip
  - systemd
  - adduser
  - libfontconfig1

# More aggressive updates for monitoring servers
update_ubuntu_host_upgrade_packages: true
update_ubuntu_host_update_cache: true
